// The position ID for ruleset major 3, written from
// `reference/start-position.md` §5 alone - never by copying the existing
// major-2 rule engine.
//
// A position ID spells out White's 16 home squares as one hexadecimal
// character per square, read **row 1 A->H, then row 2 A->H**: `1`-`5` a
// numbered piece's rank, `F` the Flag, `0` an empty square. Black's
// arrangement is derived from White's (`startPosition.ts`, Step 4) and is not
// part of the code, so the ID names the whole starting position.
//
// **It is a string throughout - never parsed into a numeric type of any
// kind.** Sixteen hexadecimal digits is 64 bits; the largest valid code
// exceeds 1.7 x 10^19, far past the 2^53 limit within which a JavaScript
// double-precision number holds integers exactly. Converting a position ID
// into one would corrupt it silently, and this is a front-end repository -
// so this module never converts a code to a number, a big integer, or
// anything else numeric, and neither may any caller: two codes are compared
// and sorted as plain strings.
//
// **Decoding and validating are different operations.** Of the 16^16 codes
// this format can express, only 1,345,344,000 are startable major-3
// positions - a density of about 7 x 10^-11. `decodePositionId` below is a
// mechanical inverse of the encoding table (it throws only when a character
// has no meaning in that table at all); `isValidPositionId` is the separate,
// stricter check for "does this code name an actual starting position" -
// exactly three of each rank digit, exactly one `F`, and that `F` among the
// first eight characters (row 1). **A position must never be generated by
// drawing a random code** and validating it - see `startPosition.ts` (Step
// 4), which generates the arrangement directly and encodes it afterward.
//
// **Case is normalised on input, before anything else.** Comparison, sorting
// and storage are all defined on the upper-cased form (`start-position.md`
// §5: "Write uppercase, and upper-case on input" - `F` is `0x46` and `f` is
// `0x66`, so a lowercase code neither compares equal to its uppercase twin
// nor sorts alongside it).
//
// This module builds on the board geometry (`board.ts`) and the rank catalog
// (`pieces.ts`), both Step 1, and the board-state model (`position.ts`),
// Step 2.

import { COLUMN_COUNT, homeSquares, type Square } from "./board.ts";
import {
  FLAG_ID_DIGIT,
  FLAG_QUANTITY_PER_SIDE,
  RANK_CATALOG,
  RANKS,
  type Rank,
  type RankIdDigit,
} from "./pieces.ts";
import {
  EMPTY_POSITION,
  pieceAt,
  placePiece,
  type PositionState,
} from "./position.ts";

/**
 * A position ID: a 16-character uppercase hexadecimal string. Kept as a
 * plain `string` type - never a numeric type of any kind - because that is
 * the whole point of this module (see module comment).
 */
export type PositionId = string;

/** A position ID is always exactly this many characters - one per White home square. */
export const POSITION_ID_LENGTH = 16;

/** The digit written for an empty square (`start-position.md` §5's encoding table). */
const EMPTY_SQUARE_DIGIT = "0";

/** The inverse of `pieces.ts`'s `RankCatalogEntry.idDigit`: id digit back to rank. Exhaustive over `Rank`. */
const RANK_BY_ID_DIGIT: Readonly<Record<RankIdDigit, Rank>> = {
  "1": 1,
  "2": 2,
  "3": 3,
  "4": 4,
  "5": 5,
};

/** White's 16 home squares, in the position ID's fixed order: row 1 A->H, then row 2 A->H. */
function positionIdSquares(): readonly Square[] {
  return homeSquares("white");
}

/**
 * Normalises `code` to the upper-cased form comparison, sorting and storage
 * are all defined on (`start-position.md` §5). Every other function in this
 * module normalises its input through this before doing anything else with
 * it.
 */
export function normalizePositionId(code: string): PositionId {
  return code.toUpperCase();
}

/** The digit `square` encodes to, read off `position`. */
function digitForSquare(position: PositionState, square: Square): string {
  const piece = pieceAt(position, square);
  if (piece === undefined) {
    return EMPTY_SQUARE_DIGIT;
  }
  if (piece.kind === "flag") {
    return FLAG_ID_DIGIT;
  }
  return RANK_CATALOG[piece.rank].idDigit;
}

/**
 * Encodes White's 16 home squares of `position` as a position ID: one
 * uppercase hexadecimal digit per square, in row-1-then-row-2 order
 * (`start-position.md` §5). Squares outside White's home rows are not read -
 * the ID names White's arrangement only, never the whole board.
 */
export function encodePositionId(position: PositionState): PositionId {
  return positionIdSquares()
    .map((square) => digitForSquare(position, square))
    .join("");
}

/**
 * Decodes `code` into White's half of a board state: a piece placed on each
 * of the 16 home squares whose digit names one (`1`-`5` a rank, `F` the
 * Flag), and no entry for a square whose digit is `0`.
 *
 * This is a mechanical inverse of the encoding table, **not** a check that
 * `code` names a legal starting position - see `isValidPositionId` for that.
 * It still throws for a code that cannot be decoded at all: the wrong length,
 * or a character with no meaning in the encoding table (`start-position.md`
 * §5's reserved digits, `6`-`E`, are unused and undefined at this major).
 */
export function decodePositionId(code: string): PositionState {
  const normalized = normalizePositionId(code);
  if (normalized.length !== POSITION_ID_LENGTH) {
    throw new Error(
      `positionId.ts: decodePositionId: expected ${POSITION_ID_LENGTH} characters, got ${normalized.length} ("${normalized}").`,
    );
  }
  const squares = positionIdSquares();
  let position: PositionState = EMPTY_POSITION;
  for (let index = 0; index < POSITION_ID_LENGTH; index += 1) {
    const digit = normalized[index];
    const square = squares[index];
    if (digit === EMPTY_SQUARE_DIGIT) {
      continue;
    }
    if (digit === FLAG_ID_DIGIT) {
      position = placePiece(position, square, { side: "white", kind: "flag" });
      continue;
    }
    const rank = RANK_BY_ID_DIGIT[digit as RankIdDigit];
    if (rank === undefined) {
      throw new Error(
        `positionId.ts: decodePositionId: "${digit}" at character ${index} of "${normalized}" is not a recognised digit at this major (expected "0", "1"-"5" or "F").`,
      );
    }
    position = placePiece(position, square, {
      side: "white",
      kind: "numbered",
      rank,
    });
  }
  return position;
}

/**
 * True if `code` names a legal major-3 starting position: exactly 16
 * characters, exactly three of each rank digit `1`-`5`, exactly one `F`, and
 * that `F` among the **first eight** characters (row 1 - `start-position.md`
 * §5, the same restriction the Flag is generated under, §1). Normalises case
 * first, so a lowercase code that would decode to a valid position validates
 * too.
 *
 * This is deliberately separate from `decodePositionId`: of the 16^16 codes
 * the format can express, only 1,345,344,000 are positions (see module
 * comment), so decoding a code successfully is not evidence it names one.
 */
export function isValidPositionId(code: string): boolean {
  const normalized = normalizePositionId(code);
  if (normalized.length !== POSITION_ID_LENGTH) {
    return false;
  }

  const counts: Partial<Record<string, number>> = {};
  for (const digit of normalized) {
    const isRankDigit = RANK_BY_ID_DIGIT[digit as RankIdDigit] !== undefined;
    if (digit !== FLAG_ID_DIGIT && !isRankDigit) {
      return false;
    }
    counts[digit] = (counts[digit] ?? 0) + 1;
  }

  const hasExactRankCounts = RANKS.every(
    (rank) =>
      counts[RANK_CATALOG[rank].idDigit] === RANK_CATALOG[rank].quantityPerSide,
  );
  if (!hasExactRankCounts || counts[FLAG_ID_DIGIT] !== FLAG_QUANTITY_PER_SIDE) {
    return false;
  }

  const flagIndex = normalized.indexOf(FLAG_ID_DIGIT);
  return flagIndex < COLUMN_COUNT;
}
